routes/web.php
<?php

use App\Http\Controllers\BannerController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CheckoutController;
use App\Http\Controllers\ColorController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RoleController;
use App\Models\Category;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'welcome']);
Route::get('/categories/{category}/product', [WelcomeController::class, 'productlist'])->name('frontend.products.index');
Route::get('/products/{product}', [WelcomeController::class, 'productDetails'])->name('frontend.products.show');

Route::post('add-to-cart/{product_id}', [CartController::class, 'addToCart'])->name('add/to-cart');
Route::get('cartpage', [CartController::class, 'cartPage'])->name('cartpage');
Route::get('cart/delete/{cart_id}', [CartController::class, 'destroy'])->name('cart.destroy');
Route::post('cart/update/{cart_id}', [CartController::class, 'quantityUpdate'])->name('cart.update');
Route::post('coupon/apply', [CartController::class, 'couponApply'])->name('coupon.apply');
Route::get('coupon/destroy', [CartController::class, 'couponDestroy'])->name('coupon.destroy');

Route::get('checkout', [CheckoutController::class, 'index'])->name('checkout.index');
Route::post('place/order', [OrderController::class, 'storOrder'])->name('place.order');
Route::get('order/success', [OrderController::class, 'orderSuccess'])->name('order.success');

Route::get('login/google', [App\Http\Controllers\Auth\AuthenticatedSessionController::class, 'redirectToGoogle'])->name('login.google');
Route::get('login/google/callback', [App\Http\Controllers\Auth\AuthenticatedSessionController::class, 'handelGoogleCallback']);

Route::get('login/facebook', [App\Http\Controllers\Auth\AuthenticatedSessionController::class, 'redirectToFacebook'])->name('login.facebook');
Route::get('login/facebook/callback', [App\Http\Controllers\Auth\AuthenticatedSessionController::class, 'handelFacebookCallback']);



require __DIR__ . '/auth.php';

Route::middleware('auth')->prefix('dashboard')->group(function () {

    Route::post('/products/{product}/comments', [CommentController::class, 'store'])->name('products.comments.store');

    Route::get('/', function () {
        return view('admin.index');
    });

    Route::get('/blkcreate', function () {
        return view('admin.blkcreate');
    });
    Route::get('/listindex', function () {
        return view('admin.listIndex');
    });


    Route::get('home', [WelcomeController::class, 'index'])->name('index');

    Route::get('home', [WelcomeController::class, 'index'])->name('home.index');
    Route::get('blog', [WelcomeController::class, 'blog'])->name('welcomes.blog');
    Route::get('blogdetails', [WelcomeController::class, 'blogDetails'])->name('blogdetails');
    Route::get('checkout', [WelcomeController::class, 'checkout'])->name('checkout');
    Route::get('shopcart', [WelcomeController::class, 'shopCart'])->name('shopcart');
    Route::get('shop', [WelcomeController::class, 'shop'])->name('shop');
    Route::get('shopdetails', [WelcomeController::class, 'shopDetails'])->name('shopdetails');
    Route::get('contact', [WelcomeController::class, 'contact'])->name('contact');

    Route::resource('banners', BannerController::class);
    Route::resource('posts', PostController::class);

    Route::get('/products/index', [ProductController::class, 'index'])->name('product.index');
    Route::get('/products/create', [ProductController::class, 'create'])->name('product.create');;
    Route::post('/products/create', [ProductController::class, 'store'])->name('product.store');
    Route::get('/products/{id}', [ProductController::class, 'show'])->name('product.show');
    Route::get('/products/{id}/edit', [ProductController::class, 'edit'])->name('product.edit');
    Route::patch('/products/{id}/update', [ProductController::class, 'update'])->name('product.update');
    Route::delete('/products/destroy/{id}', [ProductController::class, 'destroy'])->name('product.destroy');
    Route::get('/products-trash', [ProductController::class, 'trash'])->name('product.trash');
    Route::get('/products/{id}/restore', [ProductController::class, 'restore'])->name('product.restore');
    Route::delete('/products/{id}/delete', [ProductController::class, 'delete'])->name('product.delete');


    Route::get('/categories-trash', [CategoryController::class, 'trash'])->name('categories.trash');
    Route::get('/categories/{id}/restore', [CategoryController::class, 'restore'])->name('categories.restore');
    Route::delete('/categories/{id}/delete', [CategoryController::class, 'delete'])->name('categories.delete');
    Route::get('/categories-pdf', [CategoryController::class, 'pdf'])->name('categories.pdf');


    Route::get('/categories', [CategoryController::class, 'index'])->name('categories.index');
    Route::get('/categories/create', [CategoryController::class, 'create'])->name('categories.create');
    Route::post('/categories/store', [CategoryController::class, 'store'])->name('categories.store');
    Route::get('/categories/{id}', [CategoryController::class, 'show'])->name('categories.show');
    Route::delete('/categories/{id}', [CategoryController::class, 'destory'])->name('categories.destory');
    Route::get('/categories/{id}/edit', [CategoryController::class, 'edit'])->name('categories.edit');
    Route::patch('/categories/{id}/update', [CategoryController::class, 'update'])->name('categories.update');


    Route::get('/colors-trash', [ColorController::class, 'trash'])->name('colors.trash');
    Route::get('/colors/{id}/restore', [ColorController::class, 'restore'])->name('colors.restore');
    Route::delete('/colors/{id}/delete', [ColorController::class, 'delete'])->name('colors.delete');


    Route::get('/colors', [ColorController::class, 'index'])->name('colors.index');
    Route::get('/colors/create', [ColorController::class, 'create'])->name('colors.create');
    Route::post('/colors/store', [ColorController::class, 'store'])->name('colors.store');
    Route::get('/colors/{id}', [ColorController::class, 'show'])->name('colors.show');
    Route::delete('/colors/{id}', [ColorController::class, 'destory'])->name('colors.destory');
    Route::get('/colors/{id}/edit', [ColorController::class, 'edit'])->name('colors.edit');
    Route::patch('/colors/{id}/update', [ColorController::class, 'update'])->name('colors.update');

    Route::resource('coupons', CouponController::class);


    Route::get('/userlist', [ProfileController::class, 'index'])->name('user.index');
    Route::get('/user/destroy/{id}', [ProfileController::class, 'destroy'])->name('user.destroy');
    Route::get('/user/edit/{id}', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/user/update/{id}', [ProfileController::class, 'update'])->name('profile.update');

    Route::get('/user/role/{id}', [ProfileController::class, 'role'])->name('role.change');
    Route::patch('/user/role/{id}', [ProfileController::class, 'change'])->name('change.update');
    Route::get('/user-trash', [ProfileController::class, 'trash'])->name('user.trash');
    Route::get('/user/{id}/restore', [ProfileController::class, 'restore'])->name('user.restore');
    Route::delete('/user/{id}/delete', [ProfileController::class, 'delete'])->name('user.delete');
    Route::get('/user/{id}/show',[ProfileController::class, 'show'])->name('user.show');


    Route::get('/role', [RoleController::class, 'index'])->name('role.index');
    Route::get('/role/create', [RoleController::class, 'create'])->name('role.create');
    Route::post('/role/store', [RoleController::class, 'store'])->name('role.store');
    Route::get('/role/{id}', [RoleController::class, 'show'])->name('role.show');
    Route::delete('/role/{id}', [RoleController::class, 'destory'])->name('role.destroy');
    Route::get('/role/{id}/edit', [RoleController::class, 'edit'])->name('role.edit');
    Route::patch('/role/{id}/update', [RoleController::class, 'update'])->name('role.update');
    Route::get('/role-trash', [RoleController::class, 'trash'])->name('role.trash');
    Route::get('/role/{id}/restore', [RoleController::class, 'restore'])->name('role.restore');
    Route::delete('/role/{id}/delete', [RoleController::class, 'delete'])->name('role.delete');
});

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    use HasFactory;

    protected $guarded=[];
}

app/Http/Controllers/CouponController.php
<?php

namespace App\Http\Controllers;

use App\Models\Coupon;
use Illuminate\Http\Request;

class CouponController extends Controller
{
    public function index()
    {
        $coupons = Coupon::latest()->paginate(10);
        return view('admin.coupons.index', compact('coupons'));
    }

    public function create()
    {
        return view('admin.coupons.create');
    }

     public function show(Coupon $coupon)
    {
        return view('admin.coupons.show', compact('coupon')); 
    }

    public function store(Request $request)
    {
        $requestData = [
            'name' => strtoupper($request->name),
            'discount' => $request->discount
        ];

        Coupon::create($requestData);

        return redirect()
            ->route('coupons.index')
            ->withMessage('Successfully Created');
    }


    public function edit(Coupon $coupon)
    {
        return view('admin.coupons.edit', compact('coupon'));
    }

    public function update(Request $request, Coupon $coupon)
    {
        $requestData = [
            'name' => strtoupper($request->name),
            'discount' => $request->discount
        ];

        $coupon->update($requestData);

        return redirect()
            ->route('coupons.index')
            ->withMessage('Successfully Update');
    }

    public function destroy(Coupon $coupon)
    {
         $coupon->delete();

        return redirect()
            ->route('coupons.index')
            ->withMessage('Successfully Deleted');
    }


    // public function trash()
    // {
    //     $coupons = Coupon::onlyTrashed()->get();
    //     return view('admin.coupons.trash', compact('coupons'));
    // }

    // public function restore($id)
    // {
    //     $Coupon = Coupon::onlyTrashed()->find($id);
    //     $Coupon->restore();
    //     return redirect()
    //         ->route('coupons.trash')
    //         ->withMessage('Successfully restore');
    // }

    // public function delete($id)
    // {
    //     $Coupon = Coupon::onlyTrashed()->find($id);
    //     $Coupon->forceDelete();
    //     return redirect()
    //         ->route('coupons.trash')
    //         ->withMessage('Successfully deleted');
    // }

    // public function pdf()
    // {
    //     $coupons = Coupon::all();
    //     $pdf = Pdf::loadView('admin.coupons.pdf', compact('coupons'));
    //     return $pdf->download('coupons.pdf');
    // }

    // public function uploadImage($image)
    // {
        
    //     $originalname = $image->getClientOriginalName();
    //     $fileName = date('Y-m-d').time().$originalname;
    //     $image->move( storage_path('/app/public/coupons'), $fileName);

    //     return $fileName;

    // }
}

resources/views/admin/coupons/create.blade.php
<x-admin.master>
    <x-slot:title>
        Coupon Create
        </x-slot>



        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Coupon</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('coupons.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-info">
                        <i class="fa-light fa-list"></i> List
                    </button>
                </a>
            </div>
            @if (session('message'))
                <span class="text-success">{{ session('message') }}</span>
            @endif
        </div>

        {{-- <x-forms.errors /> --}}
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card shadow p-3 mb-5 bg-body rounded">
                <div class="card-body">
                    <form class="forms-sample" action="{{ route('coupons.store') }}" method="post"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <x-forms.input type="text" name="name" placeholder="Enter name" label="Name" />
                            <x-forms.input type="text" name="discount" placeholder="Discount" label="Discount" />
                        </div>
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>

</x-admin.master>

resources/views/admin/coupons/edit.blade.php
<x-admin.master>
    <x-slot:title>
        Coupon edit
        </x-slot>

        @if (session('message'))
            <span class="text-success">{{ session('message') }}</span>
        @endif

        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Coupon</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('coupons.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-info">
                        <span data-feather="list"></span>
                        List
                    </button>
                </a>
            </div>
        </div>

        <x-forms.errors />

        <div class="container bg-light rounded">
            <form action="{{ route('coupons.update', $coupon->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('patch')
                <x-forms.input type="text" name="name" value="{{ $coupon->name }}" placeholder="Enter name"
                    label="Name" />
                <x-forms.input type="text" name="discount" value="{{ $coupon->discount }}" placeholder="Discount"
                    label="Discount" />

                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>

</x-admin.master>

resources/views/admin/coupons/index.blade.php
<x-admin.master>

    <x-slot:title>Coupons</x-slot:title>
    @section('p4') active @endsection

    <x-forms.message />

    <div class="container">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Coupons</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                {{-- <div class="btn-group me-2">
                    <a href="#">
                        <button type="button" class="btn btn-sm btn-outline-warning"><i class="fa-solid fa-file-pdf"></i>
                            PDF</button>
                    </a>
                    <button type="button" class="btn btn-sm btn-outline-info"><i class="fa-regular fa-file-excel"></i>
                        Excel</button>
                    <a href="#">
                        <button type="button" class="btn btn-sm btn-outline-danger"> <i class="icon-trash"></i>
                            Trash</button>
                    </a>
                </div> --}}
                <a href="{{ route('coupons.create') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="plus"></span>
                        <i class="icon-folder"></i> Add New
                    </button>
                </a>
            </div>
        </div>

        <table class="table bg-light rounded">
            <thead class="bg-primary text-white">
                <tr>
                    <th>SL#</th>
                    <th>Name</th>
                    <th>Discount</th>
                    <th>Status</th>
                    <th width="180px">
                        <center>Action</center>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach ($coupons as $coupon)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $coupon->name }}</td>
                        <td>{{ $coupon->discount }}%</td>
                        <td>{{ $coupon->status }}</td>
                        <td>
                            <center>
                            <a href="{{ route('coupons.show', $coupon->id) }}" class="btn btn-info text-white"><i
                                    class="icon-eye"></i></a>
                            <a href="{{ route('coupons.edit', $coupon->id) }}"
                                class="btn btn-warning text-white"><i class="fa-solid fa-pen-to-square"></i></a>

                            <form action="{{ route('coupons.destroy', $coupon->id) }}" method="post"
                                style="display:inline">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger text-white"
                                    onclick="return confirm('Are you sure want to deleted?')"> <i
                                        class="icon-trash"></i>
                                </button>
                            </form>
                            </center>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</x-admin.master>

resources/views/admin/coupons/pdf.blade.php
<table>
    <thead>
        <tr>
            <th>SL#</th>
            <th>Name</th>
            {{-- <th>Image</th> --}}
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($categories as $category)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $category->name }}</td>

            {{-- <td><img src="{{ asset('storage/categories/' . $category->image) }}" alt="{{ $category->name }}"
            class="rounded-circle" style="height: 60px" width="60px"></td> --}}
            <td>{{ $category->details }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/admin/coupons/show.blade.php
<x-admin.master>
    <x-slot:title>Coupon Show</x-slot:title>


    <div class="container-fluid bg-white">
        <div class="container">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Coupon</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group me-2">

                    </div>
                    <a href="{{ route('coupons.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-primary">
                            <span data-feather="plus"></span>
                            List
                        </button>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                </div>
                <div class="col-md-6">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Name:&nbsp;<b> {{ $coupon->name }}</b></li>
                        <li class="list-group-item">Discount:&nbsp;<b> {{ $coupon->discount }}</b></li>
                    </ul>
                </div>
            </div>
        </div>


    </div>

</x-admin.master>

resources/views/admin/coupons/trash.blade.php
<x-admin.master>

    <x-slot:title>Categories trash</x-slot:title>

    <x-forms.message />

    <div class="container">
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Categories</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('categories.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-danger">List</button>
                    </a>
                </div>
            </div>
        </div>

        <table class="table bg-light rounded">
            <thead class="bg-primary">
                <tr>
                    <th>SL#</th>
                    <th>Name</th>
                    <th>Image</th>
                    <th>Details</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $category->name }}</td>

                        <td><img src="{{ asset('storage/categories/' . $category->image) }}" alt="{{ $category->name }}"
                                class="rounded-circle" style="height: 60px" width="60px"></td>
                        <td>{{ $category->details }}</td>
                        <td><a href="{{ route('categories.show', $category->id) }}" class="btn btn-info text-white"><i
                                    class="icon-eye"></i></a>
                            <a href="{{ route('categories.restore', $category->id) }}"
                                class="btn btn-primary text-white">Restore</a>

                            <form action="{{ route('categories.delete', $category->id) }}" method="post"
                                style="display:inline">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger text-white"
                                    onclick="return confirm('Are you sure want to delete?')"><i
                                        class="icon-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</x-admin.master>